"""
개발/테스트용 샘플 데이터 (크롤링 실패 시 또는 최초 실행 시 사용)
"""
from datetime import datetime, timedelta

now = datetime.utcnow()


SAMPLE_COMPETITIONS = [
    {
        "title": "2025 AI 혁신 챌린지 - 생성형 AI 서비스 아이디어 공모",
        "organization": "과학기술정보통신부",
        "category": "AI/머신러닝",
        "source_site": "linkareer",
        "source_url": "https://linkareer.com/list/contest",
        "original_url": "https://linkareer.com/list/contest",
        "deadline": now + timedelta(days=5),
        "start_date": now - timedelta(days=10),
        "prize": "최우수 500만원, 우수 300만원, 장려 100만원",
        "description": "생성형 AI 기술을 활용한 혁신적인 서비스 아이디어를 공모합니다.",
        "thumbnail": "",
    },
    {
        "title": "빅데이터 분석 경진대회 2025",
        "organization": "한국데이터산업진흥원",
        "category": "빅데이터",
        "source_site": "wevity",
        "source_url": "https://www.wevity.com",
        "original_url": "https://www.wevity.com",
        "deadline": now + timedelta(days=12),
        "start_date": now - timedelta(days=5),
        "prize": "대상 1000만원 상당 상금",
        "description": "공공데이터를 활용한 빅데이터 분석 및 시각화 경진대회입니다.",
        "thumbnail": "",
    },
    {
        "title": "국방 AI·빅데이터 활용 아이디어 공모전",
        "organization": "국방부",
        "category": "AI/머신러닝",
        "source_site": "linkareer",
        "source_url": "https://linkareer.com/list/contest",
        "original_url": "https://linkareer.com/list/contest",
        "deadline": now + timedelta(days=3),
        "start_date": now - timedelta(days=20),
        "prize": "최우수 200만원",
        "description": "국방 분야에 AI와 빅데이터를 활용하는 아이디어를 공모합니다.",
        "thumbnail": "",
    },
    {
        "title": "스마트팜 IoT 솔루션 공모전",
        "organization": "농림축산식품부",
        "category": "IoT/임베디드",
        "source_site": "thinkgood",
        "source_url": "https://www.thinkgood.co.kr",
        "original_url": "https://www.thinkgood.co.kr",
        "deadline": now + timedelta(days=25),
        "start_date": now - timedelta(days=3),
        "prize": "최우수상 300만원",
        "description": "스마트팜에 활용 가능한 IoT 기반 솔루션을 개발하는 공모전입니다.",
        "thumbnail": "",
    },
    {
        "title": "청년 모바일 앱 개발 경진대회",
        "organization": "서울특별시",
        "category": "앱개발",
        "source_site": "wevity",
        "source_url": "https://www.wevity.com",
        "original_url": "https://www.wevity.com",
        "deadline": now + timedelta(days=18),
        "start_date": now - timedelta(days=7),
        "prize": "대상 500만원, 금상 300만원",
        "description": "시민 생활 편의를 높이는 모바일 앱을 개발하는 경진대회입니다.",
        "thumbnail": "",
    },
    {
        "title": "핀테크 블록체인 해커톤 2025",
        "organization": "금융위원회",
        "category": "블록체인",
        "source_site": "linkareer",
        "source_url": "https://linkareer.com/list/contest",
        "original_url": "https://linkareer.com/list/contest",
        "deadline": now + timedelta(days=7),
        "start_date": now - timedelta(days=1),
        "prize": "총 상금 2000만원",
        "description": "블록체인 기술을 활용한 금융 서비스 혁신 아이디어 해커톤입니다.",
        "thumbnail": "",
    },
    {
        "title": "웹 접근성 개선 공모전",
        "organization": "한국웹접근성인증평가원",
        "category": "웹개발",
        "source_site": "thinkgood",
        "source_url": "https://www.thinkgood.co.kr",
        "original_url": "https://www.thinkgood.co.kr",
        "deadline": now + timedelta(days=30),
        "start_date": now,
        "prize": "우수상 150만원",
        "description": "디지털 취약계층을 위한 웹 접근성 개선 솔루션 공모전입니다.",
        "thumbnail": "",
    },
    {
        "title": "사이버 보안 CTF 경진대회",
        "organization": "한국인터넷진흥원(KISA)",
        "category": "보안/해킹",
        "source_site": "wevity",
        "source_url": "https://www.wevity.com",
        "original_url": "https://www.wevity.com",
        "deadline": now + timedelta(days=45),
        "start_date": now + timedelta(days=5),
        "prize": "대상 1000만원",
        "description": "사이버 보안 기술력을 겨루는 CTF(Capture The Flag) 경진대회입니다.",
        "thumbnail": "",
    },
    {
        "title": "데이터 시각화 경진대회 - 공공데이터 활용",
        "organization": "행정안전부",
        "category": "데이터",
        "source_site": "linkareer",
        "source_url": "https://linkareer.com/list/contest",
        "original_url": "https://linkareer.com/list/contest",
        "deadline": now + timedelta(days=14),
        "start_date": now - timedelta(days=10),
        "prize": "우수상 200만원, 장려상 50만원",
        "description": "공공데이터를 창의적으로 시각화하여 사회적 가치를 만드는 경진대회입니다.",
        "thumbnail": "",
    },
    {
        "title": "인디게임 개발 공모전 2025",
        "organization": "한국콘텐츠진흥원",
        "category": "게임/VR",
        "source_site": "thinkgood",
        "source_url": "https://www.thinkgood.co.kr",
        "original_url": "https://www.thinkgood.co.kr",
        "deadline": now + timedelta(days=60),
        "start_date": now + timedelta(days=1),
        "prize": "최우수 1000만원",
        "description": "창의적인 인디게임 개발 작품을 공모합니다. PC/모바일 모두 가능.",
        "thumbnail": "",
    },
    {
        "title": "UI/UX 디자인 & 개발 융합 공모전",
        "organization": "카카오",
        "category": "UI/UX",
        "source_site": "linkareer",
        "source_url": "https://linkareer.com/list/contest",
        "original_url": "https://linkareer.com/list/contest",
        "deadline": now + timedelta(days=21),
        "start_date": now - timedelta(days=2),
        "prize": "대상 500만원, 우수상 300만원",
        "description": "사용자 경험을 혁신하는 UI/UX 디자인 + 프론트엔드 개발 공모전입니다.",
        "thumbnail": "",
    },
    {
        "title": "LLM 기반 챗봇 서비스 개발 공모전",
        "organization": "네이버 클라우드",
        "category": "AI/머신러닝",
        "source_site": "wevity",
        "source_url": "https://www.wevity.com",
        "original_url": "https://www.wevity.com",
        "deadline": now + timedelta(days=8),
        "start_date": now - timedelta(days=15),
        "prize": "1등 800만원, 2등 400만원, 3등 200만원",
        "description": "HyperCLOVA X 기반의 혁신적인 챗봇 서비스를 개발하는 공모전입니다.",
        "thumbnail": "",
    },
]
